### ISSUE TITLE
cabal gives a warning about new style projects

### ISSUE THREAD

**Issue by devosb** [neilmayhew/RepoExplorer#1]
The [README.md](https://github.com/neilmayhew/RepoExplorer/blob/master/README.md) file says to use `cabal` to build and install the project. On Ubuntu Bionic (cabal version 1.24.0.2) this worked. With Ubuntu Focal (cabal version 2.4.0.0) I get warnings from running cabal saying
```
Warning: The update command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-update command
or the legacy v1-update alias as new-style projects will become the default in
the next version of cabal-install. Please file a bug if you cannot replicate a
working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild
```
Is the fix to use the v1- prefix to the `cabal` commands, or change the project to use the new v2 style commands?

**Comment by neilmayhew** [comment]
In later versions of `cabal` (3.x which is now in _Groovy_) the new-style commands are the default (and RepoExplorer builds just fine with them). On _Focal_, `cabal` is in the in-between state where you have to be explicit about which version of the commands you want. Unfortunately, this means the instructions need to have three versions, too, for `cabal` 1.x, 2.x and 3.x.

I'll update the README in the next day or two. In the meantime, you can just ignore the warnings.

Thanks for pointing this out.

**Comment by neilmayhew** [comment]
I think edac8e7 takes care of this. Please test the new instructions and (if the results are good) close this issue. Thanks.

**Comment by devosb** [comment]
The fix works, at least for what I could test with (`cabal` 1.x and 2.x).
